#pragma "once"

#include "fonttypes.hpp"

struct Font
{
    std::string name;
    font_t typeface;
    bool case_sensitive = false;
    int height;
};

Font default_font;

void init_font() {
    default_font.name = "default";
    default_font.height = 4;
    default_font.case_sensitive = false;
    default_font.typeface['a'].push_back("   db   ");
    default_font.typeface['a'].push_back("  dPYb  ");
    default_font.typeface['a'].push_back(" dP__Yb ");
    default_font.typeface['a'].push_back("dP\"\"\"\"Yb");
    default_font.typeface['b'].push_back("88\"\"Yb");
    default_font.typeface['b'].push_back("88__dP");
    default_font.typeface['b'].push_back("88\"\"Yb");
    default_font.typeface['b'].push_back("88oodP");
    default_font.typeface['c'].push_back(" dP\"\"b8");
    default_font.typeface['c'].push_back("dP   `\"");
    default_font.typeface['c'].push_back("Yb     ");
    default_font.typeface['c'].push_back(" YboodP");
    default_font.typeface['d'].push_back("8888b. ");
    default_font.typeface['d'].push_back(" 8I  Yb");
    default_font.typeface['d'].push_back(" 8I  dY");
    default_font.typeface['d'].push_back("8888Y\"");
    default_font.typeface['e'].push_back("888888");
    default_font.typeface['e'].push_back("88__  ");
    default_font.typeface['e'].push_back("88\"\"  ");
    default_font.typeface['e'].push_back("888888");
    default_font.typeface['f'].push_back("888888");
    default_font.typeface['f'].push_back("88__  ");
    default_font.typeface['f'].push_back("88\"\"");
    default_font.typeface['f'].push_back("88    ");
    default_font.typeface['g'].push_back(" dP\"\"b8");
    default_font.typeface['g'].push_back("dP   `\"");
    default_font.typeface['g'].push_back("Yb  \"88");
    default_font.typeface['g'].push_back(" YboodP");
    default_font.typeface['h'].push_back("88  88");
    default_font.typeface['h'].push_back("88  88");
    default_font.typeface['h'].push_back("888888");
    default_font.typeface['h'].push_back("88  88");
    default_font.typeface['i'].push_back("88");
    default_font.typeface['i'].push_back("88");
    default_font.typeface['i'].push_back("88");
    default_font.typeface['i'].push_back("88");
    default_font.typeface['j'].push_back(" 88888");
    default_font.typeface['j'].push_back("    88");
    default_font.typeface['j'].push_back("o.  88");
    default_font.typeface['j'].push_back("\"bodP'");
    default_font.typeface['k'].push_back("88  dP");
    default_font.typeface['k'].push_back("88odP ");
    default_font.typeface['k'].push_back("88\"Yb ");
    default_font.typeface['k'].push_back("88  Yb");
    default_font.typeface['l'].push_back("88    ");
    default_font.typeface['l'].push_back("88    ");
    default_font.typeface['l'].push_back("88  .o");
    default_font.typeface['l'].push_back("88ood8");
    default_font.typeface['m'].push_back("8b    d8");
    default_font.typeface['m'].push_back("88b  d88");
    default_font.typeface['m'].push_back("88YbdP88");
    default_font.typeface['m'].push_back("88 YY 88");
    default_font.typeface['n'].push_back("88b 88");
    default_font.typeface['n'].push_back("88Yb88");
    default_font.typeface['n'].push_back("88 Y88");
    default_font.typeface['n'].push_back("88  Y8");
    default_font.typeface['o'].push_back(" dP\"Yb ");
    default_font.typeface['o'].push_back("dP   Yb");
    default_font.typeface['o'].push_back("Yb   dP");
    default_font.typeface['o'].push_back(" YbodP ");
    default_font.typeface['p'].push_back("88\"\"Yb");
    default_font.typeface['p'].push_back("88__dP");
    default_font.typeface['p'].push_back("88\"\"\" ");
    default_font.typeface['p'].push_back("88    ");
    default_font.typeface['q'].push_back(" dP\"Yb");
    default_font.typeface['q'].push_back("dP   Yb");
    default_font.typeface['q'].push_back("Yb b dP");
    default_font.typeface['q'].push_back(" `\"YoYo");
    default_font.typeface['r'].push_back("88\"\"Yb");
    default_font.typeface['r'].push_back("88__dP");
    default_font.typeface['r'].push_back("88\"Yb ");
    default_font.typeface['r'].push_back("88  Yb");
    default_font.typeface['s'].push_back(".dP\"Y8");
    default_font.typeface['s'].push_back("`Ybo.\"");
    default_font.typeface['s'].push_back("o.`Y8b");
    default_font.typeface['s'].push_back("8bodP'");
    default_font.typeface['t'].push_back("888888");
    default_font.typeface['t'].push_back("  88  ");
    default_font.typeface['t'].push_back("  88  ");
    default_font.typeface['t'].push_back("  88  ");
    default_font.typeface['u'].push_back("88   88");
    default_font.typeface['u'].push_back("88   88");
    default_font.typeface['u'].push_back("Y8   8P");
    default_font.typeface['u'].push_back("`YbodP'");
    default_font.typeface['v'].push_back("Yb    dP");
    default_font.typeface['v'].push_back(" Yb  dP ");
    default_font.typeface['v'].push_back("  YbdP  ");
    default_font.typeface['v'].push_back("   YP   ");
    default_font.typeface['w'].push_back("Yb        dP");
    default_font.typeface['w'].push_back(" Yb  db  dP ");
    default_font.typeface['w'].push_back("  YbdPYbdP  ");
    default_font.typeface['w'].push_back("   YP  YP   ");
    default_font.typeface['x'].push_back("Yb  dP");
    default_font.typeface['x'].push_back(" YbdP ");
    default_font.typeface['x'].push_back(" dPYb ");
    default_font.typeface['x'].push_back("dP  Yb");
    default_font.typeface['y'].push_back("Yb  dP");
    default_font.typeface['y'].push_back(" YbdP ");
    default_font.typeface['y'].push_back("  8P  ");
    default_font.typeface['y'].push_back(" dP   ");
    default_font.typeface['z'].push_back("8888P");
    default_font.typeface['z'].push_back("  dP ");
    default_font.typeface['z'].push_back(" dP  ");
    default_font.typeface['z'].push_back("d8888");
    default_font.typeface['0'].push_back(" dP\"Yb");
    default_font.typeface['0'].push_back("dP   Yb");
    default_font.typeface['0'].push_back("Yb   dP");
    default_font.typeface['0'].push_back(" YbodP ");
    default_font.typeface['1'].push_back("  .d");
    default_font.typeface['1'].push_back(".d88");
    default_font.typeface['1'].push_back("  88");
    default_font.typeface['1'].push_back("  88");
    default_font.typeface['2'].push_back("oP\"Yb.");
    default_font.typeface['2'].push_back("\"' dP'");
    default_font.typeface['2'].push_back("  dP' ");
    default_font.typeface['2'].push_back(".d8888");
    default_font.typeface['3'].push_back("88888");
    default_font.typeface['3'].push_back("  .dP");
    default_font.typeface['3'].push_back("o `Yb");
    default_font.typeface['3'].push_back("YbodP");
    default_font.typeface['4'].push_back("  dP88 ");
    default_font.typeface['4'].push_back(" dP 88 ");
    default_font.typeface['4'].push_back("d888888");
    default_font.typeface['4'].push_back("    88 ");
    default_font.typeface['5'].push_back("888888");
    default_font.typeface['5'].push_back("88oo.\"");
    default_font.typeface['5'].push_back("   `8b");
    default_font.typeface['5'].push_back("8888P'");
    default_font.typeface['6'].push_back("  dP'  ");
    default_font.typeface['6'].push_back(".d8'   ");
    default_font.typeface['6'].push_back("8P\"\"\"Yb");
    default_font.typeface['6'].push_back("`YboodP");
    default_font.typeface['7'].push_back("888888P");
    default_font.typeface['7'].push_back("    dP ");
    default_font.typeface['7'].push_back("   dP  ");
    default_font.typeface['7'].push_back("  dP   ");
    default_font.typeface['8'].push_back(".dP\"o.");
    default_font.typeface['8'].push_back("`8b.d'");
    default_font.typeface['8'].push_back("d'`Y8b");
    default_font.typeface['8'].push_back("`bodP'");
    default_font.typeface['9'].push_back("dP\"\"Yb");
    default_font.typeface['9'].push_back("Ybood8");
    default_font.typeface['9'].push_back("  .8P'");
    default_font.typeface['9'].push_back(" .dP' ");
    default_font.typeface['-'].push_back("        ");
    default_font.typeface['-'].push_back("        ");
    default_font.typeface['-'].push_back("\"\"\"\"\"\"\"\"");
    default_font.typeface['-'].push_back("        ");
    default_font.typeface['+'].push_back("   oo   ");
    default_font.typeface['+'].push_back("___88___");
    default_font.typeface['+'].push_back("\"\"\"88\"\"\"");
    default_font.typeface['+'].push_back("   \"\"   ");
    default_font.typeface['*'].push_back("   o   ");
    default_font.typeface['*'].push_back("`8.8.8'");
    default_font.typeface['*'].push_back(".8.8.8.");
    default_font.typeface['*'].push_back("   \"   ");
    default_font.typeface['/'].push_back("   dP");
    default_font.typeface['/'].push_back("  dP ");
    default_font.typeface['/'].push_back(" dP  ");
    default_font.typeface['/'].push_back("dP   ");
    default_font.typeface['='].push_back("      ");
    default_font.typeface['='].push_back("oooooo");
    default_font.typeface['='].push_back("      ");
    default_font.typeface['='].push_back("\"\"\"\"\"\"");
    default_font.typeface[','].push_back("    ");
    default_font.typeface[','].push_back("    ");
    default_font.typeface[','].push_back(" .o.");
    default_font.typeface[','].push_back(",dP'");
    default_font.typeface['.'].push_back("    ");
    default_font.typeface['.'].push_back("    ");
    default_font.typeface['.'].push_back(".o.");
    default_font.typeface['.'].push_back("`\"'");
    default_font.typeface['!'].push_back("d8b");
    default_font.typeface['!'].push_back("Y8P");
    default_font.typeface['!'].push_back("`\"'");
    default_font.typeface['!'].push_back("(8)");
    default_font.typeface['\\'].push_back("Yb   ");
    default_font.typeface['\\'].push_back(" Yb  ");
    default_font.typeface['\\'].push_back("  Yb ");
    default_font.typeface['\\'].push_back("   Yb");
    default_font.typeface['|'].push_back("II");
    default_font.typeface['|'].push_back("II");
    default_font.typeface['|'].push_back("II");
    default_font.typeface['|'].push_back("II");
    default_font.typeface['\''].push_back(" .o.");
    default_font.typeface['\''].push_back(",dP'");
    default_font.typeface['\''].push_back("    ");
    default_font.typeface['\''].push_back("    ");
    default_font.typeface['"'].push_back("o8o o8o");
    default_font.typeface['"'].push_back("`\"' `\"'");
    default_font.typeface['"'].push_back("       ");
    default_font.typeface['"'].push_back("       ");
    default_font.typeface[' '].push_back("       ");
    default_font.typeface[' '].push_back("       ");
    default_font.typeface[' '].push_back("       ");
    default_font.typeface[' '].push_back("       ");
    default_font.typeface['\n'].push_back("\n");
    default_font.typeface['\n'].push_back("\n");
    default_font.typeface['\n'].push_back("\n");
    default_font.typeface['\n'].push_back("\n");
}